#!/usr/bin/python3

def max_integer(lst=[]):
    if not isinstance(lst, list):
        raise TypeError("Check that you passed a list")
    if len(lst) == 0:
        return None
    max_ = lst[0]
    for val in lst:
        if val > max_:
            max_ = val
    return max_
